set(_CATKIN_CURRENT_PACKAGE "mbzirc_task2")
set(mbzirc_task2_MAINTAINER "cam <cam@todo.todo>")
set(mbzirc_task2_DEPRECATED "")
set(mbzirc_task2_VERSION "0.0.0")
set(mbzirc_task2_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(mbzirc_task2_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(mbzirc_task2_BUILDTOOL_DEPENDS "catkin")