set(mbzirc_task2_SETUP_PY_VERSION "0.0.0")
set(mbzirc_task2_SETUP_PY_SCRIPTS "")
set(mbzirc_task2_SETUP_PY_PACKAGES "model_import")
set(mbzirc_task2_SETUP_PY_PACKAGE_DIRS "src/model_import")
set(mbzirc_task2_SETUP_PY_MODULES "")
set(mbzirc_task2_SETUP_PY_MODULE_DIRS "")